### ISSUE TITLE
Setting up a paymentclient documentation is no longer correct

### ISSUE THREAD

**Issue by Sippelberg** [I-Synergy/Mollie.Net#23]
In the latest update this line of code doesn't work anymore:
IPaymentClient paymentClient = new PaymentClient("{yourApiKey}");

new PaymentClient now requires clientService object which isn't documented.

**Comment by IsmailHassani** [comment]
Dear @Sippelberg,
I've updated the documentation.
Btw, i didn't receive a notification of your created issue. i'll check that out and my apologies for the late reaction.
